### ISSUE TITLE
Add in 2 missing facilities DEC State Facility Air State Permit Records

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data#113]
@SPTKL  I'd like your help with this.  EARD flagged that DEC State Facility Air State Permit record with permit id `2-6105-00009/02003` is missing.  This is because the zipcode on the record is `12207` which is an Albany zip code.  The FACILITY CITY value is BROOKLYN and the address is 122-68 FLATLANDS AVE, which is a BROOKLYN address.  How do you propose we get this record into the output?
Here's what I thought of:
1) When filtering input data filter by zipcode as well as FACILITY CITY is FACILITY CITY is "BROOKLYN", "STATEN ISLAND", "QUEENS", "MANHATTAN", "BRONX" and assign borough value.  Everything should work downstream
2) Add in record manually

**Comment by AmandaDoyle** [comment]
@SPTKL After reviewing the new nysdec_state_facility_permits output I notice that using the `facility name` isn't working as intended
1) There is at least one record outside of NYC that is getting mapped and added to the output
Permit id `9-1430-00122/00020` has a facility city value of CHEEKTOWAGA and zip code 14225, and an address of 3101 BROADWAY.  3101 BROADWAY Queens is a valid address but there isn't a facility there.
2) The intent of the geo_rejects is to report records in NYC that weren't mapped that need to be manually researched and geocoded by EARD.  Now it has records outside of NYC.  
3) There is at least one record that is in NYC that isn't getting geocoded and added to the output, and is in the `geo_rejects` table
Permit id `2-6203-00017/00007` has a facility city value of WARDS ISLAND and zip code 10035, and an address of 600 E 125TH ST.  600 E 125TH ST Manhattan, which is what 10035 maps to, is a valid address.
I'm happy to workshop this so that we get the simplest solution that works

**Comment by SPTKL** [comment]
can EARD just give us a list of permit ids that they want to include? the data quality is too bad for us to auto filter and isn't worth it to implement complicated logic

**Comment by AmandaDoyle** [comment]
@SPTKL Here is a csv with the list of permit ids that need to be included in output `nysdec_state_facility_permits`
[nysdec_state_facility_permits_permit_ids.csv.zip](https://github.com/NYCPlanning/ceqr-app-data/files/7170792/nysdec_state_facility_permits_permit_ids.csv.zip)

**Comment by damonmcc** [comment]
see [comment in relevant closed PR](https://github.com/NYCPlanning/ceqr-app-data/pull/116#issuecomment-1533689689)
