### ISSUE TITLE
Update CEQR schools data tables

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data#152]
**Update the following tables for CP:**
- sca_e_projections_by_sd
- sca_e_projections_by_boro
- sca_capacity_projects (with subd)

**Source tables:**
For enrollment projections (sca_e_projections_by_sd and sca_e_projections_by_boro)
- 2021-2030 Enroll Projection By Grade UPDATED maps to `sca_e_projections`, which is the name of the source data in the code.
- 2024 ENROLLMENT % by Zone maps to `sca_e_pct`, which is the name of the source data in the code.
It looks like it's been so long since we updated these data table that there are no templates for the source data in data library.  We'll need to create the templates and upload the data into data library.  Refer to scripts [here](https://github.com/NYCPlanning/ceqr-app-data/tree/main/recipes/sca_e_projections_by_boro) and [here](https://github.com/NYCPlanning/ceqr-app-data/tree/main/recipes/sca_e_projections_by_sd) for field names of source data.

For capacity projects (sca_capacity_projects)
- Section 6_ Capacity Projects in Process_Feb2022 maps to `sca_capacity_projects_current`, which is the name of the source data in the code.
- No source data for `sca_capacity_projects_prev` and `sca_capacity_projects_tcu`

**Steps to make update:**
- Load source data into data library
- Point pipelines to retrieve data from data library
- Run pipelines
- Deliver outputs directly to Capital Planning

**Roadblocks**
- Determine what to do for missing datasets for capacity projects.

**Comment by mbh329** [comment]
It looks like there will have to be some refactoring of the code as well to make it compatible with our current infrastructure (i.e. Digital Ocean). Are there links to the source data that you've mentioned above like the `2021-2030 Enroll Projection By Grade UPDATED` ?

**Comment by damonmcc** [comment]
> It looks like there will have to be some refactoring of the code as well to make it compatible with our current infrastructure (i.e. Digital Ocean). Are there links to the source data that you've mentioned above like the `2021-2030 Enroll Projection By Grade UPDATED` ?

to follow-up: all data was emailed as excel files from the Capital Planning team, converted to csv files, and archived to the `edm-data.recipes` DB

currently awaiting review of outputs by DE team and will share with Capital Planning
