### ISSUE TITLE
Backup and upgrade ceqr-data Postgres database cluster

### ISSUE THREAD

**Issue by TylerMatteo** [NYCPlanning/ceqr-app-data#170]
We need to upgrade the `ceqr-data` postgres cluster in Digital Ocean off of version 11 before it reaches End of Life. According to DO's built-in upgrade functionality, we can automatically upgrade to v13, which is supported until Nov 13, 2025.

![Image](https://github.com/NYCPlanning/ceqr-app-data/assets/9055367/47d800c2-18f6-4ebc-be2b-e15778db6771)

## Steps
1. Download backups of the `ceqr-data` and `ceqr_data_staging` databases in the `ceqr-data` cluster
2. Verify that you can restore from those backups by restoring them to a local postgres cluster
3. Upload the backups to the `ae-data-backups` Space in digital ocean under the `ceqr-data` folder
4. Upgrade the `ceqr-data` cluster to version 13 by navigating to the overview page for the cluster in DO, clicking "Show Available Upgrades", selecting PostgreSQL 13, and "Upgrade Now"

**Comment by TangoYankee** [comment]
I assigned this issue to myself. However, I do not have permission to update the Assignee field.

**Comment by TangoYankee** [comment]
~~Steps 1-3 are complete~~ All steps are complete
