### ISSUE TITLE
Add documentation for refactored code

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/ceqr-app-data#20]
This includes: in/out schema documentation for the sql scripts, docstrings for python functions, within-script comments, and README
- [ ] README
- [x] atypical_roadways (BC)
- [x] ceqr_school_buildings (MG)
- [x] ctpp_censustract_centroids (BC)
- [x] ctpp_censustract_variables (BC)
- [x] ctpp_journey_to_work (BC)
- [x] dcp_areas_of_concern (MG)
- [x] dep_cats_permits (MG)
- [ ] doe_significant_utilization_changes (not refactored yet -- need more information about source data)
- [x] dot_traffic_cameras (MG)
- [x] facilities_garages (BC)
- [x] nysdec_air_monitoring_stations (MG)
- [x] nysdec_state_facility_permits (MG)
- [x] nysdec_title_v_facility_permits (MG)
- [x] nysdot_aadt (BC)
- [x] nysdot_functional_class (BC)
- [x] nysdot_traffic_counts (MG)
- [x] sca_capacity_projects (MG)
- [x] sca_e_projections_by_boro (BC)
- [x] sca_e_projections_by_sd (BC)
- [x] tunnel_ventilation_towers (MG)

**Comment by SPTKL** [comment]
the `out` schema is kind of recorded in the `create.sql` files. Also should we record these in wiki or the `.sql` files?

**Comment by mgraber** [comment]
> the `out` schema is kind of recorded in the `create.sql` files. Also should we record these in wiki or the `.sql` files?

The schema recorded in the CREATE comment in `create.sql` matches what gets read in to the EDM database, not necessarily what get output as the final schema, right? For example, several different geosupport fields can be used to determine geometry and then get dropped from final output. I think there is value in both documentation places. Having comments in the scripts themselves seems helpful for internal documentation so we can remember how and why we did things and more easily read our own code.

**Comment by SPTKL** [comment]
#40
