### ISSUE TITLE
Update dep_cats_permits on a monthly basis

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/ceqr-app-data#46]
NYCPlanning/edm-overview#689

DEP cats permits source data: https://data.cityofnewyork.us/api/views/f4rp-2kvy/rows.csv
Create scheduled github actions to pull from opendata and run recipe.

**Comment by SPTKL** [comment]
workflow -> #47

**Comment by SPTKL** [comment]
Documentation:
- still need to automatically generate PDF for the README file (check out pandoc -> https://pandoc.org/) 
- ~~still need to figure out how to place the metadata.xlsx file~~

**Comment by SPTKL** [comment]
complete
